[package]
name = "familyphotos"
authors = ["Filea Răzvan Gheorghe <razvan.filea@gmail.com>"]
version = "3.0.0"
edition = "2021"

[profile.release]
incremental = true
lto = "thin"

[dependencies]
# Async Runtime
tokio = { version = "1", features = ["rt-multi-thread", "fs", "io-std"] }
tokio-util = { version = "0.7", features = ["io"]}
async-trait = "0.1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rayon = "1.7"

# Axum
axum = { version = "0.6", features = ["multipart"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["trace"] }
axum-server = { version = "0.4", features = ["tls-rustls"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Database
diesel = { version = "2.0", default-features = false, features = ["32-column-tables", "postgres", "time", "uuid"] }
diesel_migrations = "2.0"
diesel-async = { version = "0.2", features = ["postgres", "bb8"] }
bb8 = "0.8"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Rand
rand = "0.8"
rand_hc = "0.3"

# Utils
clap = { version = "4.2", features = ["derive", "cargo"] }
lazy_static = "1"
regex = "1"
uuid = "1.3"
wait-timeout = "0.2"
time = { version = "0.3", features = ["macros", "parsing"] }
dotenv = "0"
walkdir = "2.3"
mime_guess = "2"

# Crypto
base64 = "0.21"
sha2 = "0.10"

# Images
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "png", "webp", "hdr", "webp-encoder"] }
kamadak-exif = "0.5"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
