[package]
name = "familyphotos"
authors = ["Filea Răzvan Gheorghe <razvan.filea@gmail.com>"]
version = "3.0.0"
edition = "2021"

[profile.release]
incremental = true
lto = "thin"

[dependencies]
# Async Runtime
tokio = { version = "1.27", features = ["rt-multi-thread", "fs", "io-std"] }
tokio-util = { version = "0.7", features = ["io"]}
async-trait = "0.1"

# Axum
axum = { version = "0.6", features = ["multipart"] }
tower = "0.4"

# Https
axum-server = { version = "0.4", features = ["tls-rustls"] }
rustls = "0.20"

# Database
diesel = { version = "2.0", default-features = false, features = ["32-column-tables", "postgres", "time"] }
diesel_migrations = "2.0"
diesel-async = { version = "0.2", features = ["postgres", "bb8"] }
bb8 = "0.8"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
env_logger = { version = "0.10", default-features = false, features = ["humantime", "color"] }
log = "0.4"

# Rand
rand = "0.8"
rand_hc = "0.3"

# Utils
clap = { version = "4.2", features = ["derive", "cargo"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rayon = "1.7"
lazy_static = "1"
regex = "1"
wait-timeout = "0.2"
time = { version = "0.3", features = ["macros", "parsing"] }
dotenv = "0"
walkdir = "2.3"
mime_guess = "2"

# Crypto
base64 = "0.21"
sha2 = "0.10"

# Images
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "png", "webp", "hdr", "webp-encoder"] }
kamadak-exif = "0.5"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
