[package]
name = "familyphotos"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
incremental = true
lto = "thin"

[dependencies]
actix = "0.13.0"
actix-web = "4.1.0"
actix-web-httpauth = "0.8.0"
#validator = { version = "0.16.0", features = ["derive"] }
chrono = { version = "^0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "1.1.2", features = ["v4", "serde"] }
diesel = { version = "2.0.0-rc.1", features = ["uuid", "r2d2", "postgres", "chrono"] }
#diesel_migrations = "2.0.0-rc.1"
env_logger = "0.9.0"
log = "^0.4"
dotenv = "0.15.0"
