[package]
name = "familyphotos"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
incremental = true
lto = "thin"

[dependencies]
actix = "0.13.0"
actix-web = { version = "4.1", default-features = false, features = ["macros", "openssl"] }
actix-web-httpauth = "^0.8"
openssl = "^0.10"
actix-multipart = "^0.4"
local-channel = "^0.1"
chrono = { version = "^0.4", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
diesel = { version = "2.0.0-rc.1", features = ["r2d2", "postgres", "chrono"] }
#diesel_migrations = "2.0.0-rc.1"
env_logger = "0.9.0"
log = "^0.4"
dotenv = "0.15.0"
walkdir = "^2.3"
rand = "^0.8"
rand_hc = "0.3.1"
futures-util = { version = "^0.3", default-features = false, features = ["std"] }
lazy_static = "^1"
regex = "^1"
kamadak-exif = "^0.5"
base64 = "^0.13"
sha2 = "^0.10"