[package]
name = "familyphotos"
authors = ["Filea Răzvan-Gheorghe <razvan.filea@gmail.com>"]
version = "3.1.0"
edition = "2021"

[profile.release]
incremental = true
lto = "fat"

[dependencies]
# Async Runtime
tokio = { version = "1", features = ["rt-multi-thread", "fs", "io-std"] }
tokio-util = { version = "0.7", features = ["io"]}
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rayon = "1.8"
async-trait = "0.1"

# Axum
axum = { version = "0.7", features = ["multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
axum-server = { version = "0.5", features = ["tls-rustls"] }
axum-login = "0.10"
tower-sessions = { version = "0.7", default-features = false, features = ["postgres-store"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio", "macros", "time", "postgres"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Rand
rand = "0.8"

# Utils
clap = { version = "4.4", features = ["derive", "cargo"] }
lazy_static = "1"
regex = "1"
wait-timeout = "0.2"
time = { version = "0.3", features = ["macros", "parsing"] }
dotenvy = "0.15"
walkdir = "2.4"
mime_guess = "2"

# Crypto
argon2 = { version = "0.5", features = ["std"] }

# Images
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "png", "webp", "hdr"] }
kamadak-exif = "0.5"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[profile.dev.package.sqlx-macros]
opt-level = 3
