[package]
name = "familyphotos"
authors = ["Filea Răzvan Gheorghe <razvan.filea@gmail.com>"]
version = "2.4.4"
edition = "2021"

[profile.release]
incremental = true
lto = "thin"

[dependencies]
# Actix
actix = "0.13"
actix-web = { version = "4", default-features = false, features = ["macros", "rustls"] }
actix-web-httpauth = "0.8"
actix-files = "0.6"
actix-multipart = "0.6"
rustls = "0.20"
rustls-pemfile = "1.0"

# Database
diesel = { version = "2.0", default-features = false, features = ["32-column-tables", "r2d2", "postgres", "time"] }
diesel_migrations = "2.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
env_logger = { version = "0.10", default-features = false, features = ["humantime", "color"] }
log = "0.4"

# Rand
rand = "0.8"
rand_hc = "0.3"

# Utils
clap = { version = "4.2", features = ["derive", "cargo"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rayon = "1.7"
lazy_static = "1"
regex = "1"
wait-timeout = "0.2"
time = { version = "0.3", features = ["macros", "parsing"] }
dotenv = "0"
walkdir = "2.3"

# Crypto
base64 = "0.21"
sha2 = "0.10"

# Images
image = { version = "0.24", default-features = false, features = ["gif", "jpeg", "png", "webp", "hdr", "webp-encoder"] }
kamadak-exif = "0.5"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"
